# Generated by Django 4.0.5 on 2022-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_employeedetail_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='hudumanumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
