# Generated by Django 4.0.5 on 2022-06-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_employeedetail_hudumanumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
