# Generated by Django 4.0.5 on 2022-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_employeedetail_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='bankdetails',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='contact',
            new_name='bankbranch',
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='Acnumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
