# Generated by Django 4.0.5 on 2022-06-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_employeedetail_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='Acnumber',
            new_name='acnumber',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='ID',
            new_name='idnumber',
        ),
    ]
