# Generated by Django 4.0.5 on 2022-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_rename_acnumber_employeedetail_acnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='city',
            field=models.TextField(default='', max_length=100),
        ),
    ]
